name: Release

on:
  push:
    tags:
      - 'release-v*'

permissions:
  contents: write

jobs:
  promote-to-production:
    name: Push to production branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push to production branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin HEAD:production --force
